name: app-ci
on:
  push:
    branches: [ main, develop ]
  pull_request:
concurrency:
  group: app-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9.6.0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm build:deterministic
      - run: pnpm start -- -p 3001 &
      - run: npx wait-on http-get://localhost:3001
      - name: Conformance tests (Playwright)
        run: BASE_URL="http://localhost:3001" pnpm test:api:v1:conformance
      - name: Setup k6
        uses: grafana/setup-k6-action@v1
      - name: Latency budget (k6)
        run: BASE_URL="http://localhost:3001" pnpm k6:budget
