name: db-guard
on:
  push:
    branches: [ main, develop ]
  pull_request:
concurrency:
  group: db-guard-${{ github.ref }}
  cancel-in-progress: true
jobs:
  guard:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9.6.0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20.11.1, cache: 'pnpm' }
      - run: pnpm install --silent
      - run: pnpm db:report
      - name: Attach report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: db_report
          path: _tmp/db_report.json
