name: secrets-guard
on:
  push:
    branches: [ main, develop ]
  pull_request:
concurrency:
  group: secrets-guard-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Validate required secrets
        env:
          S1: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          S2: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          S3: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          missing=0
          for k in S1 S2 S3; do
            v="${!k}"
            if [ -z "$v" ]; then
              echo "::error title=Missing secret::Required secret $k is not set"
              missing=1
            fi
          done
          if [ $missing -eq 1 ]; then
            echo "::error::One or more required secrets are missing. Configure at: https://github.com/${{ github.repository }}/settings/secrets/actions"
            exit 1
          fi
          echo "✅ All required secrets are configured"
